AWSTemplateFormatVersion: '2010-09-09'
Description: A compliant template
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: 'sample-fargate-taskdef'
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: 'arn:aws:iam::123456789012:role/ecsTaskExecutionRole'
      TaskRoleArn: 'arn:aws:iam::123456789012:role/ecsTaskRole'
      ContainerDefinitions:
        - Name: 'nginx'
          Cpu: 256
          Memory: 512
          Image: 'nginx'
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: 'sample-fargate-logs'
              awslogs-region: 'us-west-2'
              awslogs-stream-prefix: 'nginx'
