AWSTemplateFormatVersion: '2010-09-09'
Description: A compliant template
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: 'sample-fargate-taskdef'
      Cpu: 1024
      Memory: 2056
      NetworkMode: host
      ExecutionRoleArn: 'arn:aws:iam::123456789012:role/ecsTaskExecutionRole'
      TaskRoleArn: 'arn:aws:iam::123456789012:role/notAllowedRole'
      ContainerDefinitions:
        - Name: 'nginx'
          Image: 'nginx'
          Privileged: true
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: 'sample-fargate-logs'
              awslogs-region: 'us-west-2'
              awslogs-stream-prefix: 'nginx'
